import { AlertTriangle, ArrowUpRight, Brain, Ear, Eye, Hand, HeartPulse, MessageCircle, Radio, Scale, ShieldCheck, Sparkles, Waves } from "lucide-react";

const abilities=[
  { icon:Eye, name:"Clairvoyance", translation:"clear seeing", text:"Inner images, symbols, scenes, colors, or visual impressions interpreted as information beyond ordinary sight." },
  { icon:Ear, name:"Clairaudience", translation:"clear hearing", text:"Words, tones, names, or messages experienced internally and interpreted as intuitive hearing." },
  { icon:HeartPulse, name:"Clairsentience", translation:"clear feeling", text:"Bodily sensations or emotional impressions interpreted as information about a person, place, or situation." },
  { icon:Brain, name:"Claircognizance", translation:"clear knowing", text:"A sudden sense of knowing without a consciously recognized chain of reasoning." },
  { icon:Waves, name:"Clairalience & Clairgustance", translation:"clear smelling & tasting", text:"Unexpected smell or taste impressions interpreted symbolically or as information." },
  { icon:Hand, name:"Psychometry", translation:"object reading", text:"Impressions reportedly received while holding an object or entering a location associated with a person or event." },
  { icon:MessageCircle, name:"Mediumship", translation:"deceased-focused", text:"The reported reception of information attributed specifically to deceased human beings." },
  { icon:Radio, name:"Channeling", translation:"source-focused", text:"Speaking, writing, or creating information attributed to a source outside ordinary conscious awareness." },
  { icon:Sparkles, name:"Automatic Writing", translation:"flow state", text:"Writing produced with reduced conscious planning and interpreted through spiritual, creative, or psychological lenses." },
  { icon:Eye, name:"Remote Viewing", translation:"structured perception", text:"Protocols that attempt to describe distant or hidden targets while controlling ordinary information access." },
];

const figures=[
  { name:"Lee Carroll", source:"Kryon", years:"Public work since 1989", color:"#2FFFE0", summary:"Carroll says he channels Kryon, described in his work as a benevolent angelic intelligence. His books helped popularize Kryon and the Indigo Children concept internationally.", context:"The messages are spiritual claims, not independently verified communications. Critics have challenged the movement’s scientific language and some associated claims.", links:[["Official Kryon biography","https://kryon.com/Leebio-statement.html"],["Neutral overview","https://en.wikipedia.org/wiki/Lee_Carroll"]] },
  { name:"Esther Hicks", source:"Abraham", years:"Public work since the 1980s", color:"#FFE24A", summary:"Hicks presents Abraham as a collective of non-physical teachers. The Abraham-Hicks material centers the Law of Attraction, deliberate creation, and the art of allowing.", context:"The teaching belongs to the broader New Thought and prosperity-consciousness lineage. Its source claims are matters of belief rather than established fact.", links:[["Official biography","https://abraham-hicks.com/esther-hicks-official-biography/"],["Critical historical context","https://skepticalinquirer.org/2023/08/abraham-hicks-motivational-speaking-spirits/"]] },
  { name:"Darryl Anka", source:"Bashar", years:"Public work since 1983", color:"#39A7FF", summary:"Anka says he channels Bashar, described as an extraterrestrial being from a parallel reality and a future-related version of himself. His work emphasizes beliefs, excitement, choice, and parallel realities.", context:"Anka has acknowledged that Bashar’s existence cannot be scientifically proved and encourages evaluating the material by its practical usefulness.", links:[["Official Darryl Anka page","https://www.bashar.org/darryl-anka"],["About the material","https://www.bashar.org/about"]] },
  { name:"Edgar Cayce", source:"The sleeping prophet", years:"1877–1945", color:"#FF7900", summary:"Cayce entered self-induced trance states and gave more than 14,000 documented readings on health, spirituality, reincarnation, and ancient civilizations. The A.R.E. preserves his archive.", context:"Cayce is historically important to modern metaphysical spirituality. Scholars and critics debate whether the readings reflected anomalous information, suggestion, or existing esoteric literature.", links:[["Virginia biography","https://www.lva.virginia.gov/public/dvb/bio.asp?b=Cayce_Edgar"],["A.R.E. archive guide","https://guides.loc.gov/religion-collections-libraries-archives/va-association-for-research-enlightenment-a-r-e-library"]] },
];

const lenses=[
  ["Spiritual lens","Information is understood as communication from guides, consciousness, spirits, or non-physical beings."],
  ["Psychological lens","The material may emerge through dissociation, imagination, intuition, implicit memory, archetype, or creative flow."],
  ["Parapsychology lens","Controlled studies investigate anomalous information while attempting to rule out cueing, fraud, and ordinary inference."],
  ["Skeptical lens","Cold reading, expectancy, confirmation bias, source memory, performance, and social reinforcement are considered first."],
];

export default function IntuitiveArtsPage(){return <div className="page intuitive-page"><section className="intuitive-hero"><div><p className="kicker">Intuition & channeling atlas</p><h1 data-testid="intuitive-heading">The many ways people say<br/>they <em>receive.</em></h1><p data-testid="intuitive-description">A respectful guide to psychic vocabulary, channeling history, notable figures, research, skepticism, and the discernment needed to explore unusual experiences without surrendering agency.</p></div><div className="intuitive-mark" aria-hidden="true"><Eye/><span>experience</span><span>belief</span><span>research</span><span>discernment</span></div></section>
<section className="ability-section" data-testid="psychic-abilities-section"><div className="section-heading"><p className="kicker">The vocabulary</p><h2>The “clairs” and related practices</h2><p>These labels describe how practitioners interpret experiences. A label names a reported mode of reception; it does not establish the source or accuracy of the information.</p></div><div className="ability-grid">{abilities.map(({icon:Icon,name,translation,text},index)=><article key={name} data-testid={`psychic-ability-${index+1}`}><Icon/><small>{translation}</small><h3>{name}</h3><p>{text}</p></article>)}</div></section>
<section className="channeling-lenses" data-testid="channeling-lenses-section"><div><p className="kicker">Four honest lenses</p><h2>What could channeling be?</h2><p>No single framework currently settles every reported experience. Strong inquiry compares possibilities instead of forcing one conclusion.</p></div><div>{lenses.map(([title,text],index)=><article key={title} data-testid={`channeling-lens-${index+1}`}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="channeler-section" data-testid="channeler-profiles-section"><div className="section-heading"><p className="kicker">People & transmitted voices</p><h2>Notable channelers in context</h2><p>Each profile separates what the practitioner says, what can be documented historically, and what remains belief or dispute.</p></div><div className="channeler-list">{figures.map((figure,index)=><article key={figure.name} style={{"--figure-color":figure.color}} data-testid={`channeler-profile-${index+1}`}><header><span>0{index+1}</span><div><small>{figure.years}</small><h3>{figure.name}</h3><p>{figure.source}</p></div></header><div><p>{figure.summary}</p><p className="profile-context">{figure.context}</p><div>{figure.links.map(([label,url],linkIndex)=><a href={url} target="_blank" rel="noreferrer" key={label} data-testid={`channeler-${index+1}-source-${linkIndex+1}`}>{label}<ArrowUpRight/></a>)}</div></div></article>)}</div></section>
<section className="discernment-code" data-testid="channeling-discernment-section"><div><ShieldCheck/><p className="kicker">The discernment code</p><h2>A meaningful message should not require your surrender.</h2></div><ul><li><strong>Keep consent central.</strong><span>No guide, teacher, or entity overrides bodily autonomy or boundaries.</span></li><li><strong>Refuse urgency and fear.</strong><span>Be cautious when a message demands immediate money, obedience, secrecy, or isolation.</span></li><li><strong>Protect high-stakes choices.</strong><span>Do not replace medical, legal, financial, or safety guidance with channeling.</span></li><li><strong>Check the record.</strong><span>Write predictions before outcomes, note misses as well as hits, and test alternative explanations.</span></li><li><strong>Watch daily functioning.</strong><span>If experiences prevent sleep, create fear, command harm, or disrupt ordinary life, seek qualified human support promptly.</span></li></ul></section>
<section className="intuitive-note" data-testid="intuitive-safety-note"><AlertTriangle/><p><strong>Unusual experiences are not automatically illness—and spiritual framing is not automatically proof.</strong> The safest approach protects meaning, curiosity, reality testing, and access to appropriate care at the same time.</p><Scale/></section></div>}