import { AlertTriangle, BadgeCheck, Binary, Bot, CalendarRange, Fingerprint, Scale, Search, TreePine } from "lucide-react";

const methods=[
  { icon:Bot, system:"Evolving companion", engine:"Claude Sonnet 4.6 + consented retrieval", state:"Live", confidence:"Model-assisted reflection", text:"Streams nuanced responses and retrieves only memories the member explicitly chose to keep. It never claims consciousness, diagnosis, or authority over the user." },
  { icon:Binary, system:"Numerology", engine:"Transparent Pythagorean reduction", state:"Live", confidence:"Deterministic", text:"Uses the 1–9 letter cycle, preserves master numbers 11, 22, and 33, and exposes every named field rather than inventing hidden scores." },
  { icon:CalendarRange, system:"Western astrology", engine:"Tropical date preview", state:"Preview", confidence:"Birth-date level", text:"The current free layer identifies Sun sign, element, modality, polarity, and ruler. A licensed high-precision ephemeris is required before houses, aspects, Moon, or Ascendant are presented as calculated." },
  { icon:CalendarRange, system:"Chinese astrology", engine:"Sexagenary year preview", state:"Preview", confidence:"Year-level with warning", text:"Returns animal, element, and polarity while flagging Lunar New Year uncertainty. Full BaZi will require solar terms, longitude, true solar time, and verified calendar regression tests." },
  { icon:Fingerprint, system:"Human Design", engine:"Verified ephemeris stack required", state:"Held back", confidence:"No fabricated chart", text:"Type, Authority, Profile, Centers, Gates, and design-date calculations remain withheld until a commercially safe engine can be validated against known reference charts." },
  { icon:TreePine, system:"Kabbalah", engine:"Source-context interpretation", state:"Interpretive", confidence:"Tradition—not calculation", text:"The Tree of Life is not reduced to a pseudo-scientific personality algorithm. Readings distinguish Jewish mystical sources, later esoteric adaptations, symbolism, and reflective interpretation." },
  { icon:Search, system:"Knowledge search", engine:"Curated lexical retrieval", state:"Live", confidence:"Exact and contextual match", text:"Search ranks topic titles, worlds, lenses, and summaries. Semantic retrieval will be added only when the source library is large enough to improve relevance measurably." },
  { icon:Scale, system:"Path recommendations", engine:"Transparent cold-start rules", state:"Live", confidence:"User-selected intent", text:"New visitors choose their actual need and receive a clear first path. Behavioral optimization will not override stated intent or manipulate vulnerable users." },
];

export default function MethodsPage(){return <div className="page methods-page"><section className="methods-hero"><div><p className="kicker">Methods & accuracy</p><h1 data-testid="methods-heading">The strongest method<br/><em>that can be defended.</em></h1><p data-testid="methods-description">There is no single greatest algorithm for spirituality. SHANE-AI uses the best suitable engine for each task, publishes what it does, and refuses to fabricate precision where a tradition is interpretive or a calculation is not yet verified.</p></div><BadgeCheck/></section><section className="method-list" data-testid="method-list">{methods.map(({icon:Icon,system,engine,state,confidence,text},index)=><article key={system} data-testid={`method-${index+1}`}><div className="method-index"><span>0{index+1}</span><Icon/></div><div><small>{state}</small><h2>{system}</h2><p>{text}</p></div><div className="method-meta"><span><strong>Engine</strong>{engine}</span><span><strong>Confidence</strong>{confidence}</span></div></article>)}</section><section className="method-principle" data-testid="method-principle"><AlertTriangle/><div><p className="kicker">The non-negotiable</p><h2>Never manufacture certainty.</h2><p>A less impressive honest answer is better than a beautiful false one. Every engine must be testable, versioned, culturally contextualized, and replaceable when a stronger verified method becomes available.</p></div></section></div>}